using OtekBillingMetering.Business.Models.BillingModels;
using OtekBillingMetering.Execution.Abstractions.Persistence.Repositories.Base;

namespace OtekBillingMetering.Execution.Abstractions.Persistence.Repositories.Read.BillingReadRepositories;

public interface IBillingCompanyClientReadRepository : IReadRepository<BillingCompanyClient>;
